server:
  compression:
    enabled: true
    mime-types: 
      - application/json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
    min-response-size: 2048
  forward-headers-strategy: NATIVE
  server-header: "PHP/7.3.1"
  shutdown: GRACEFUL
  undertow:
    direct-buffers: true
  servlet:
    encoding:
      enabled: true
      charset: UTF-8

logging:
   config: classpath:logback-spring.xml

spring:
  application:
    name: Twitter

  lifecycle:
    timeout-per-shutdown-phase: 30
  
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      resolve-lazily: false
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 1MB

  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    converters:
      referred-json-mapper: gson

  resources:
    static-locations:
      - classpath:/static/

  freemarker:
    enabled: true
    cache: true
    content-type: text/html
    charset: utf-8
    suffix: .ftl
    request-context-attribute: request
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    check-template-location: true
    template-loader-path:
      - classpath:/templates/
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
  
